adding "enhanced privacy" mode youtube URLto CSP
raumzeitlabor/rzl-homepage-docker pull request #6
Opened 2018-05-25 13:32 UTC by tabascoeye

since we want the "enhanced privacy" mode for our embedded youtube clips, we need to add that new URL to the content-security-policy header

2018-05-25 17:22 UTC, Ranlvor approved these changes
Die Änderungen sehen gut aus. Aber ich habe keine Ahnung, wie man sowas deployt.

2018-05-26 14:21 UTC, Ranlvor requested changes
Müsste die Änderung auch bei Zeile 68 durchgeführt werden?

2018-05-26 14:25 UTC, Ranlvor commented
Habe deloyed.

2018-05-26 15:17 UTC, blabber commented
Danke 👍 

Zumindest das Video auf der Startseite, das schon auf "erweiterten Datenschutz" umgestellt war, funktioniert jetzt bei mir wieder.

2018-05-29 18:11 UTC, merged